import Link from "next/link";
import { BookCard } from "@/components/book-card";
import { CategoryCard } from "@/components/category-card";
import { SearchBox } from "@/components/search-box";
import { books, categories } from "@/data/books";

export default function HomePage() {
  return <><section className="overflow-hidden bg-gradient-to-br from-forest-100 via-white to-lime-100 py-16 sm:py-24"><div className="container-page grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><p className="mb-4 inline-flex rounded-full bg-white px-4 py-2 text-sm font-black text-forest-700 shadow-sm">🎨 ระบายสี สนุก เรียนรู้</p><h1 className="max-w-2xl text-5xl font-black leading-[1.05] tracking-tight text-forest-900 sm:text-6xl">สีสันแห่งความสุข<br /><span className="text-forest-600">เริ่มต้นได้ทุกวัน</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">หนังสือระบายสีแสนสนุกสำหรับนักสร้างสรรค์ตัวน้อย เลือกเรื่องที่ชอบ แล้วปล่อยให้จินตนาการโลดแล่น</p><div className="mt-8"><SearchBox /></div></div><div className="relative mx-auto w-full max-w-md"><div className="aspect-square rounded-[3rem] bg-forest-600 p-8 shadow-soft"><div className="grid h-full place-items-center rounded-[2rem] border-4 border-dashed border-white/60 bg-forest-500 text-center text-white"><div><span className="block text-8xl">🖍️</span><p className="mt-4 text-2xl font-black">Color your world!</p><p className="mt-1 font-bold text-forest-100">Happy Coloring Book</p></div></div></div><span className="absolute -left-7 top-10 text-5xl">🌼</span><span className="absolute -right-4 bottom-4 text-5xl">🌈</span></div></div></section><section className="container-page py-16"><div className="mb-8 flex items-end justify-between gap-4"><div><p className="font-bold text-forest-600">เลือกตามความสนใจ</p><h2 className="section-title mt-1">หมวดหมู่ยอดนิยม</h2></div><Link href="/categories" className="font-black text-forest-700">ดูทั้งหมด →</Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category) => <CategoryCard key={category.slug} category={category} />)}</div></section><section className="bg-white py-16"><div className="container-page"><div className="mb-8"><p className="font-bold text-forest-600">พร้อมให้สนุกแล้ว</p><h2 className="section-title mt-1">เล่มแนะนำสำหรับคุณ</h2></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{books.filter((book) => book.featured).map((book) => <BookCard key={book.slug} book={book} />)}</div></div></section></>;
}
